### ISSUE TITLE
Missing pinecone namespace for the final upstreams

### ISSUE THREAD

**Issue by madhuroopa** [SartajBhuvaji/Resonate#20]
<img width="503" alt="image" src="https://github.com/SartajBhuvaji/Resonate/assets/22576343/f58623be-8ed5-48c1-827c-a3aba4bad866">

- No namespace is mentioned for the append records, so it is getting appended to the default namespace. Please mention the namespace parameter

**Comment by SartajBhuvaji** [comment]
Oh yes. Nice catch!

**Comment by SartajBhuvaji** [comment]
Fix added in #22 Added Pinecone serverless with delta conversations 

Attached sample JSON Store file below.
[namespace2.json](https://github.com/SartajBhuvaji/Resonate/files/14076599/namespace2.json)

**Comment by SartajBhuvaji** [comment]
PR Merged, fixing the issue.
